vbash: T7575: Update to bash 5.2.37

diff --git a/tests/run-varenv b/tests/run-varenv
--- a/tests/run-varenv
+++ b/tests/run-varenv
@@ -1,2 +1,4 @@
-${THIS_SH} ./varenv.sh | grep -v '^expect' > /tmp/xx
-diff /tmp/xx varenv.right && rm -f /tmp/xx
+echo "warning: some of these tests will fail if arrays have not" >&2
+echo "warning: been compiled into the shell" >&2
+${THIS_SH} ./varenv.tests 2>&1 | grep -v '^expect' > ${BASH_TSTOUT}
+diff ${BASH_TSTOUT} varenv.right && rm -f ${BASH_TSTOUT}
diff --git a/tests/run-vredir b/tests/run-vredir
--- a/tests/run-vredir
+++ b/tests/run-vredir
@@ -1,2 +1,4 @@
-${THIS_SH} ./vredir.tests > /tmp/xx 2>&1
-diff /tmp/xx vredir.right && rm -f /tmp/xx
+echo "warning: the text of a system error message may vary between systems and" >&2
+echo "warning: produce diff output." >&2
+${THIS_SH} ./vredir.tests > ${BASH_TSTOUT} 2>&1
+diff ${BASH_TSTOUT} vredir.right && rm -f ${BASH_TSTOUT}
